### ISSUE TITLE
can't build..

### ISSUE THREAD

**Issue by larabear** [p2/OAuth2App#1]
Hi! I'm new to swift and I'm having trouble building the app.
I checked out OAuth2App and OAuth2. I added OAuth2.xcodeproj to the OAuth2App folder, and added target dependencies on OAuth2 and OAuth2iOS in build phases. However, I failed to build the app.

`OAuth2WebViewController.swift:21:8: No such module 'UIKit'no such module 'UIKit'`

OAuth2iOS:
`Code Sign error: No code signing identities found: No valid signing identities (i.e. ?certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'`
`CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'`

**Comment by p2** [comment]
Two things:
1. You shouldn't need to manually add anything to the app if you do a _recursive_ checkout. I'll add this to the readme.
2. This is an OS X app, it seems you are trying to run this on iOS

**Comment by p2** [comment]
(To be clear, it looks like you've added the iOS framework to the app. Do a fresh checkout as now written in the README and it should work out-of-the-box.)
